twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10

      teleop_node:
        topic   : cmd_vel_joy 
        timeout : 0.5
        priority: 10
      