twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 100

      joy_stick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 10
    